productionSimulation:
  post:
    tags:
      - ProductionSimulation
    operationId: simulateProductionFromInputs
    summary: Simulate production from manually informed input quantities
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '../schemas/production-simulation.yaml#/ProductionSimulationRequest'
    responses:
      '200':
        description: Simulation result
        content:
          application/json:
            schema:
              $ref: '../schemas/production-simulation.yaml#/ProductionSimulationResponse'
  get:
    tags:
      - ProductionSimulation
    operationId: simulateProduction
    summary: Simulate production
    parameters:
      - name: recipeId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      - name: quantity
        in: query
        required: true
        schema:
          type: number
    responses:
      '200':
        description: Simulation result
        content:
          application/json:
            schema:
              $ref: '../schemas/production-simulation.yaml#/ProductionSimulationResponse'
