ProductionCreateRequest:
  type: object
  required:
    - recipeId
    - producedQuantity
  properties:
    recipeId:
      type: integer
      format: int64
    producedQuantity:
      type: number

ProductionResponse:
  type: object
  properties:
    id:
      type: integer
      format: int64
    recipeId:
      type: integer
      format: int64
    recipeName:
      type: string
    outputItemId:
      type: integer
      format: int64
    outputItemName:
      type: string
    producedQuantity:
      type: number
    totalCost:
      type: number
    unitCost:
      type: number
    createdAt:
      type: string
      format: date-time