package br.com.bratatouille.management.common.error;

public enum ApiErrorCode {
    VALIDATION_ERROR,
    INVALID_REQUEST,
    BUSINESS_RULE_VIOLATION,
    NOT_FOUND,
    CONFLICT,
    UNAUTHORIZED,
    FORBIDDEN,
    AUTH_INVALID_CREDENTIALS,
    AUTH_USER_INACTIVE,
    AUTH_LOGIN_NOT_ALLOWED,
    AUTH_BOOTSTRAP_ALREADY_COMPLETED,
    AUTH_USERNAME_ALREADY_EXISTS,
    AUTH_CUSTOMER_ROLE_VIA_ECOMMERCE,
    INTERNAL_SERVER_ERROR
}
